name: lsbmp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - certifi=2022.12.7
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - ncurses=6.4
  - openssl=1.1.1w
  - pip=22.3.1
  - pthread-stubs=0.3
  - python=3.7.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.38.4
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - anyio==3.7.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - astor==0.8.1
      - attrs==24.2.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.0.0
      - cffi==1.15.1
      - cycler==0.11.0
      - debugpy==1.7.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.1
      - fonttools==4.38.0
      - gast==0.2.2
      - google-pasta==0.2.0
      - grpcio==1.62.3
      - h5py==2.10.0
      - idna==3.10
      - importlib-metadata==6.7.0
      - importlib-resources==5.12.0
      - ipykernel==6.16.2
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jsonschema==4.17.3
      - jupyter-client==7.4.9
      - jupyter-core==4.12.0
      - jupyter-server==1.24.0
      - jupyterlab-pygments==0.2.2
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - markdown==3.4.4
      - markupsafe==2.1.5
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - nbclassic==1.2.0
      - nbclient==0.7.4
      - nbconvert==7.6.0
      - nbformat==5.8.0
      - nest-asyncio==1.6.0
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==1.18.5
      - opt-einsum==3.3.0
      - packaging==24.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pkgutil-resolve-name==1.3.10
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.48
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pygments==2.17.2
      - pyparsing==3.1.4
      - pyrsistent==0.19.3
      - python-dateutil==2.9.0.post0
      - pyzmq==26.2.1
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.4.1
      - tensorboard==1.15.0
      - tensorflow==1.15.5
      - tensorflow-estimator==1.15.1
      - termcolor==2.3.0
      - terminado==0.17.1
      - tinycss2==1.2.1
      - tornado==6.2
      - traitlets==5.9.0
      - typing-extensions==4.7.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websocket-client==1.6.1
      - werkzeug==2.2.3
      - wrapt==1.16.0
      - zipp==3.15.0
